# Generated by Django 4.2.28 on 2026-03-06 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_grade_school'),
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubjectscore',
            name='grade',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.term')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
            ],
        ),
        migrations.AddField(
            model_name='examsubjectscore',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Exam.exam'),
            preserve_default=False,
        ),
    ]
