# Generated by Django 4.2.28 on 2026-03-10 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_studentdiscipline'),
        ('Exam', '0002_examsubjectscore_grade_exam_examsubjectscore_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubjectConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.IntegerField()),
                ('paper_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='grade',
            field=models.CharField(default='5', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('name', 'year', 'term', 'grade')},
        ),
        migrations.CreateModel(
            name='ExamSubjectPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('paper_number', models.IntegerField()),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.examsubjectconfiguration')),
            ],
        ),
        migrations.AddField(
            model_name='examsubjectconfiguration',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.exam'),
        ),
        migrations.AddField(
            model_name='examsubjectconfiguration',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.subject'),
        ),
    ]
