# Generated by Django 4.2.28 on 2026-03-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_academicyear_is_active_alter_term_is_active'),
        ('Exam', '0003_examsubjectconfiguration_exam_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubjectpaper',
            name='out_of',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('name', 'year', 'term')},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='grade',
        ),
    ]
