# Generated by Django 4.2.28 on 2026-03-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0004_examsubjectpaper_out_of_alter_exam_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsubjectpaper',
            name='out_of',
            field=models.IntegerField(),
        ),
    ]
