# Generated by Django 6.0.1 on 2026-03-11 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0005_alter_examsubjectpaper_out_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsubjectscore',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examsubjectscore',
            name='subject',
        ),
        migrations.AddField(
            model_name='examsubjectscore',
            name='paper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Exam.examsubjectpaper'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ScoreRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField()),
                ('grade', models.CharField(choices=[('EE', 'EE'), ('ME', 'ME'), ('AE', 'AE'), ('BE', 'BE')], max_length=10)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.examsubjectconfiguration')),
            ],
        ),
    ]
