# Generated by Django 4.2.28 on 2026-03-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_academicyear_is_active_alter_term_is_active'),
        ('Exam', '0006_remove_examsubjectscore_exam_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examsubjectconfiguration',
            unique_together={('exam', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='examsubjectpaper',
            unique_together={('exam_subject', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='examsubjectscore',
            unique_together={('paper', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='scoreranking',
            unique_together={('subject', 'min_score', 'max_score')},
        ),
    ]
