# Generated by Django 4.2.29 on 2026-03-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0007_alter_examsubjectconfiguration_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='period',
            field=models.CharField(choices=[('Mid Term', 'Mid Term'), ('End Term', 'End Term'), ('Opener', 'Opener'), ('Mock', 'Mock'), ('CAT', 'CAT'), ('Final', 'Final')], default='Opener', max_length=100),
            preserve_default=False,
        ),
    ]
