# Generated by Django 4.2.29 on 2026-03-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0008_exam_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
