# Generated by Django 4.2.29 on 2026-03-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0009_exam_is_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='is_running',
            field=models.BooleanField(default=True),
        ),
    ]
