# Generated by Django 6.0.3 on 2026-03-16 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0011_exam_created_at_exam_created_by_exam_updated_at_and_more'),
        ('core', '0017_studentprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubjectscore',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.class'),
        ),
    ]
