# Generated by Django 4.2.28 on 2026-03-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_studentdiscipline'),
        ('users', '0002_myuser_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='guardians', to='core.student'),
        ),
    ]
