# Generated by Django 4.2.28 on 2026-03-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_studentdiscipline'),
        ('users', '0004_alter_myuser_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='guardians', to='core.student'),
        ),
    ]
