# Generated by Django 4.2.29 on 2026-03-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_myuser_first_name_myuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Accountant', 'Accountant'), ('Receptionist', 'Receptionist'), ('Guardian', 'Guardian')], default='Admin', max_length=20),
        ),
    ]
