# Generated by Django 4.2.29 on 2026-03-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_myuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_exam_manager',
            field=models.BooleanField(default=False),
        ),
    ]
