# Generated by Django 4.2.28 on 2026-03-06 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_grade_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.school'),
            preserve_default=False,
        ),
    ]
