# Generated by Django 4.2.28 on 2026-03-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_exammode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='name',
        ),
    ]
