# Generated by Django 4.2.28 on 2026-03-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_academicyear_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='term',
            name='start_date',
        ),
    ]
