# Generated by Django 4.2.28 on 2026-03-06 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_examsubjectscore_grade_exam_examsubjectscore_exam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_remove_term_end_date_remove_term_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherClassProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
