# Generated by Django 4.2.28 on 2026-03-06 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_attendancesession_studentattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], default='Minor', max_length=20)),
                ('description', models.TextField()),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='core.student')),
            ],
        ),
    ]
