# Generated by Django 4.2.28 on 2026-03-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_academicyear_is_active_term_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='term',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
