# Generated by Django 4.2.29 on 2026-03-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_class_class_teacher_class_invigilator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammode',
            name='school',
        ),
    ]
