# Generated by Django 4.2.29 on 2026-03-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_exammode_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_boarder',
            field=models.BooleanField(default=False),
        ),
    ]
