# Generated by Django 6.0.3 on 2026-03-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_student_is_boarder'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Graduated', 'Graduated'), ('Transferred', 'Transferred'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
