# Generated by Django 4.2.29 on 2026-03-13 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_student_is_boarder'),
        ('accounts', '0004_alter_feestructure_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='student_type',
            field=models.CharField(choices=[('day', 'Day Scholar'), ('boarder', 'Boarder')], default='day', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('academic_year', 'term', 'school', 'student_type')},
        ),
    ]
