# Generated by Django 4.2.29 on 2026-03-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_feestructure_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='previous_balance',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
    ]
