# Generated by Django 4.2.29 on 2026-03-13 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_invoice_current_balance_invoice_previous_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.feestructure'),
        ),
    ]
