# Generated by Django 4.2.29 on 2026-03-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportassignment',
            name='custom_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override route fee (useful for half months)', max_digits=10, null=True),
        ),
    ]
