# Generated by Django 4.2.29 on 2026-03-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_transportassignment_custom_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='monthly_fee',
            new_name='one_way_fee',
        ),
        migrations.AddField(
            model_name='route',
            name='round_trip_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='trip_type',
            field=models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], default='round_trip', max_length=20),
        ),
        migrations.AlterField(
            model_name='transportassignment',
            name='custom_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override standard fee', max_digits=10, null=True),
        ),
    ]
