# Generated by Django 4.2.29 on 2026-03-13 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_student_is_boarder'),
        ('transport', '0003_rename_monthly_fee_route_one_way_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportassignment',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.term'),
        ),
        migrations.AlterField(
            model_name='transportassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_assignments', to='core.student'),
        ),
        migrations.AlterUniqueTogether(
            name='transportassignment',
            unique_together={('student', 'academic_year', 'term', 'is_active')},
        ),
        migrations.AddConstraint(
            model_name='transportassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'academic_year', 'term'), name='unique_active_assignment_per_term'),
        ),
    ]
